# What program(s) have to be built
PROGRAMS = ex2

# Dependencies for the program(s) to build
ex2: ../common/remregs.o ../common/wperror.o ../common/robot.o ex2.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc