# What program(s) have to be built
PROGRAMS = ex3

# Dependencies for the program(s) to build
ex3: ../common/remregs.o ../common/wperror.o ../common/robot.o ../common/utils.o ex3.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc